-- Création de la base de données
CREATE DATABASE IF NOT EXISTS tifosi;

-- Création de l'utilisateur et attribution des droits
CREATE USER IF NOT EXISTS 'tifosi'@'localhost' IDENTIFIED BY 'CEFdevoirtifosi2024';
GRANT ALL PRIVILEGES ON tifosi.* TO 'tifosi'@'localhost';
FLUSH PRIVILEGES;

-- Utilisation de la base de données
USE tifosi;

-- Création de la table MARQUE
CREATE TABLE IF NOT EXISTS MARQUE (
  ID_MARQUE INT AUTO_INCREMENT PRIMARY KEY,
  NOM_MARQUE VARCHAR(100) NOT NULL
);

-- Création de la table BOISSON
CREATE TABLE IF NOT EXISTS BOISSON (
        ID_BOISSON INT AUTO_INCREMENT PRIMARY KEY,
        NOM_BOISSON VARCHAR(100) NOT NULL,
        ID_MARQUE INT,
        FOREIGN KEY (ID_MARQUE) REFERENCES MARQUE(ID_MARQUE)
);

-- Création de la table CLIENT
CREATE TABLE IF NOT EXISTS CLIENT (
  ID_CLIENT INT AUTO_INCREMENT PRIMARY KEY,
  NOM_CLIENT VARCHAR(45) NOT NULL,
  AGE_CLIENT INT NOT NULL,
  CP_CLIENT INT NOT NULL
);

-- Création de la table FOCACCIA
 CREATE TABLE IF NOT EXISTS FOCACCIA (
  ID_FOCACCIA INT AUTO_INCREMENT PRIMARY KEY,
  NOM_FOCACCIA VARCHAR(45) NOT NULL,
  PRIX_FOCACCIA FLOAT NOT NULL
 );

 -- Création de la table ACHETER
 CREATE TABLE IF NOT EXISTS ACHETER (
  ID_CLIENT INT,
  ID_FOCACCIA INT,
  PRIMARY KEY (ID_CLIENT, ID_FOCACCIA),
  JOUR DATE,
  FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
  FOREIGN KEY (ID_FOCACCIA) REFERENCES FOCACCIA(ID_FOCACCIA)
 );

 -- Création de la table MENU
 CREATE TABLE IF NOT EXISTS MENU (
  ID_MENU INT AUTO_INCREMENT PRIMARY KEY,
  NOM_MENU VARCHAR(45) NOT NULL,
  PRIX_MENU FLOAT NOT NULL,
  ID_FOCACCIA INT,
  FOREIGN KEY (ID_FOCACCIA) REFERENCES FOCACCIA(ID_FOCACCIA)
 );

 -- Création de la table PAYER
 CREATE TABLE IF NOT EXISTS PAYER (
  ID_CLIENT INT,
  ID_MENU INT,
  PRIMARY KEY (ID_CLIENT, ID_MENU),
  JOUR DATE,
  FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
  FOREIGN KEY (ID_MENU) REFERENCES MENU(ID_MENU)
 );

 -- Création de la table CONTIENT
 CREATE TABLE IF NOT EXISTS CONTIENT (
  ID_MENU INT,
  ID_BOISSON INT,
  PRIMARY KEY (ID_MENU, ID_BOISSON),
  FOREIGN KEY (ID_MENU) REFERENCES MENU(ID_MENU),
  FOREIGN KEY (ID_BOISSON) REFERENCES BOISSON(ID_BOISSON)
 );

 -- Création de la table INGREDIENT
 CREATE TABLE IF NOT EXISTS INGREDIENT (
  ID_INGREDIENT INT AUTO_INCREMENT PRIMARY KEY,
  NOM_INGREDIENT VARCHAR(45) NOT NULL
 );

 -- Création de la table COMPRENDRE
 CREATE TABLE IF NOT EXISTS COMPRENDRE (
  ID_INGREDIENT INT,
  ID_FOCACCIA INT,
  PRIMARY KEY (ID_INGREDIENT, ID_FOCACCIA),
  FOREIGN KEY (ID_FOCACCIA) REFERENCES FOCACCIA(ID_FOCACCIA),
  FOREIGN KEY (ID_INGREDIENT) REFERENCES INGREDIENT(ID_INGREDIENT)
 );